// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Block.proto

package protobufs

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// log name space
type Metadata struct {
	Namespace            map[string]string `protobuf:"bytes,1,rep,name=namespace" json:"namespace,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetNamespace() map[string]string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

// A single log entry for a specific timestamp.
type LogLine struct {
	TimeStamp            *int64   `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Content              *string  `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogLine) Reset()         { *m = LogLine{} }
func (m *LogLine) String() string { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()    {}
func (*LogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{1}
}

func (m *LogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLine.Unmarshal(m, b)
}
func (m *LogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLine.Marshal(b, m, deterministic)
}
func (m *LogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLine.Merge(m, src)
}
func (m *LogLine) XXX_Size() int {
	return xxx_messageInfo_LogLine.Size(m)
}
func (m *LogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLine.DiscardUnknown(m)
}

var xxx_messageInfo_LogLine proto.InternalMessageInfo

func (m *LogLine) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *LogLine) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

// Contains one or more log segments as provided by LogsProcessors and read by Workers.
type LogLineSet struct {
	Key                  *string    `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Metadata             *Metadata  `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	LogLines             []*LogLine `protobuf:"bytes,3,rep,name=log_lines,json=logLines" json:"log_lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogLineSet) Reset()         { *m = LogLineSet{} }
func (m *LogLineSet) String() string { return proto.CompactTextString(m) }
func (*LogLineSet) ProtoMessage()    {}
func (*LogLineSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{2}
}

func (m *LogLineSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLineSet.Unmarshal(m, b)
}
func (m *LogLineSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLineSet.Marshal(b, m, deterministic)
}
func (m *LogLineSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLineSet.Merge(m, src)
}
func (m *LogLineSet) XXX_Size() int {
	return xxx_messageInfo_LogLineSet.Size(m)
}
func (m *LogLineSet) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLineSet.DiscardUnknown(m)
}

var xxx_messageInfo_LogLineSet proto.InternalMessageInfo

func (m *LogLineSet) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogLineSet) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *LogLineSet) GetLogLines() []*LogLine {
	if m != nil {
		return m.LogLines
	}
	return nil
}

// Used by Workers to update Governors about active namespaces they hold
type NameSpaceWorkerTuple struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	StartTime            *int64    `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	WorkerId             *int32    `protobuf:"varint,3,opt,name=workerId" json:"workerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NameSpaceWorkerTuple) Reset()         { *m = NameSpaceWorkerTuple{} }
func (m *NameSpaceWorkerTuple) String() string { return proto.CompactTextString(m) }
func (*NameSpaceWorkerTuple) ProtoMessage()    {}
func (*NameSpaceWorkerTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{3}
}

func (m *NameSpaceWorkerTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameSpaceWorkerTuple.Unmarshal(m, b)
}
func (m *NameSpaceWorkerTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameSpaceWorkerTuple.Marshal(b, m, deterministic)
}
func (m *NameSpaceWorkerTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameSpaceWorkerTuple.Merge(m, src)
}
func (m *NameSpaceWorkerTuple) XXX_Size() int {
	return xxx_messageInfo_NameSpaceWorkerTuple.Size(m)
}
func (m *NameSpaceWorkerTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_NameSpaceWorkerTuple.DiscardUnknown(m)
}

var xxx_messageInfo_NameSpaceWorkerTuple proto.InternalMessageInfo

func (m *NameSpaceWorkerTuple) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NameSpaceWorkerTuple) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *NameSpaceWorkerTuple) GetWorkerId() int32 {
	if m != nil && m.WorkerId != nil {
		return *m.WorkerId
	}
	return 0
}

// Internal aggregated set of log segments stored and accessed as a unit.
type LogBlock struct {
	BlockHeader          *LogBlock_Header `protobuf:"bytes,1,opt,name=block_header,json=blockHeader" json:"block_header,omitempty"`
	LogLines             []*LogLine       `protobuf:"bytes,2,rep,name=log_lines,json=logLines" json:"log_lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogBlock) Reset()         { *m = LogBlock{} }
func (m *LogBlock) String() string { return proto.CompactTextString(m) }
func (*LogBlock) ProtoMessage()    {}
func (*LogBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{4}
}

func (m *LogBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogBlock.Unmarshal(m, b)
}
func (m *LogBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogBlock.Marshal(b, m, deterministic)
}
func (m *LogBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogBlock.Merge(m, src)
}
func (m *LogBlock) XXX_Size() int {
	return xxx_messageInfo_LogBlock.Size(m)
}
func (m *LogBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_LogBlock.DiscardUnknown(m)
}

var xxx_messageInfo_LogBlock proto.InternalMessageInfo

func (m *LogBlock) GetBlockHeader() *LogBlock_Header {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *LogBlock) GetLogLines() []*LogLine {
	if m != nil {
		return m.LogLines
	}
	return nil
}

type LogBlock_Header struct {
	StartTime            *int64    `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime              *int64    `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogBlock_Header) Reset()         { *m = LogBlock_Header{} }
func (m *LogBlock_Header) String() string { return proto.CompactTextString(m) }
func (*LogBlock_Header) ProtoMessage()    {}
func (*LogBlock_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{4, 0}
}

func (m *LogBlock_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogBlock_Header.Unmarshal(m, b)
}
func (m *LogBlock_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogBlock_Header.Marshal(b, m, deterministic)
}
func (m *LogBlock_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogBlock_Header.Merge(m, src)
}
func (m *LogBlock_Header) XXX_Size() int {
	return xxx_messageInfo_LogBlock_Header.Size(m)
}
func (m *LogBlock_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_LogBlock_Header.DiscardUnknown(m)
}

var xxx_messageInfo_LogBlock_Header proto.InternalMessageInfo

func (m *LogBlock_Header) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *LogBlock_Header) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *LogBlock_Header) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// select (selectRegEx) from (metadata[optionally partial]) for time (time1) to (time2) where (whereRegEx)
type QueryRequest struct {
	RequestId            *int32    `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	StartTime            *int64    `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime              *int64    `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	SelectRegEx          *string   `protobuf:"bytes,5,opt,name=selectRegEx" json:"selectRegEx,omitempty"`
	WhereRegEx           *string   `protobuf:"bytes,6,opt,name=whereRegEx" json:"whereRegEx,omitempty"`
	IsRegEx              *bool     `protobuf:"varint,7,opt,name=isRegEx" json:"isRegEx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{5}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *QueryRequest) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *QueryRequest) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *QueryRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *QueryRequest) GetSelectRegEx() string {
	if m != nil && m.SelectRegEx != nil {
		return *m.SelectRegEx
	}
	return ""
}

func (m *QueryRequest) GetWhereRegEx() string {
	if m != nil && m.WhereRegEx != nil {
		return *m.WhereRegEx
	}
	return ""
}

func (m *QueryRequest) GetIsRegEx() bool {
	if m != nil && m.IsRegEx != nil {
		return *m.IsRegEx
	}
	return false
}

type QueryRequestBlockList struct {
	RequestId            *int32      `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	Metadata             []*Metadata `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty"`
	SelectRegEx          *string     `protobuf:"bytes,3,opt,name=selectRegEx" json:"selectRegEx,omitempty"`
	WhereRegEx           *string     `protobuf:"bytes,4,opt,name=whereRegEx" json:"whereRegEx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryRequestBlockList) Reset()         { *m = QueryRequestBlockList{} }
func (m *QueryRequestBlockList) String() string { return proto.CompactTextString(m) }
func (*QueryRequestBlockList) ProtoMessage()    {}
func (*QueryRequestBlockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{6}
}

func (m *QueryRequestBlockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequestBlockList.Unmarshal(m, b)
}
func (m *QueryRequestBlockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequestBlockList.Marshal(b, m, deterministic)
}
func (m *QueryRequestBlockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequestBlockList.Merge(m, src)
}
func (m *QueryRequestBlockList) XXX_Size() int {
	return xxx_messageInfo_QueryRequestBlockList.Size(m)
}
func (m *QueryRequestBlockList) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequestBlockList.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequestBlockList proto.InternalMessageInfo

func (m *QueryRequestBlockList) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *QueryRequestBlockList) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *QueryRequestBlockList) GetSelectRegEx() string {
	if m != nil && m.SelectRegEx != nil {
		return *m.SelectRegEx
	}
	return ""
}

func (m *QueryRequestBlockList) GetWhereRegEx() string {
	if m != nil && m.WhereRegEx != nil {
		return *m.WhereRegEx
	}
	return ""
}

// left join query1 with query2
type LeftJoinRequest struct {
	LeftQueryRequest     *QueryRequest `protobuf:"bytes,1,opt,name=leftQueryRequest" json:"leftQueryRequest,omitempty"`
	RightQueryRequest    *QueryRequest `protobuf:"bytes,2,opt,name=rightQueryRequest" json:"rightQueryRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LeftJoinRequest) Reset()         { *m = LeftJoinRequest{} }
func (m *LeftJoinRequest) String() string { return proto.CompactTextString(m) }
func (*LeftJoinRequest) ProtoMessage()    {}
func (*LeftJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{7}
}

func (m *LeftJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeftJoinRequest.Unmarshal(m, b)
}
func (m *LeftJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeftJoinRequest.Marshal(b, m, deterministic)
}
func (m *LeftJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeftJoinRequest.Merge(m, src)
}
func (m *LeftJoinRequest) XXX_Size() int {
	return xxx_messageInfo_LeftJoinRequest.Size(m)
}
func (m *LeftJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeftJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeftJoinRequest proto.InternalMessageInfo

func (m *LeftJoinRequest) GetLeftQueryRequest() *QueryRequest {
	if m != nil {
		return m.LeftQueryRequest
	}
	return nil
}

func (m *LeftJoinRequest) GetRightQueryRequest() *QueryRequest {
	if m != nil {
		return m.RightQueryRequest
	}
	return nil
}

type QueryResponse struct {
	RequestId            *int32             `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	LogLines             []*LogLine         `protobuf:"bytes,2,rep,name=logLines" json:"logLines,omitempty"`
	Tx                   *TransactionReport `protobuf:"bytes,4,opt,name=tx" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{8}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *QueryResponse) GetLogLines() []*LogLine {
	if m != nil {
		return m.LogLines
	}
	return nil
}

func (m *QueryResponse) GetTx() *TransactionReport {
	if m != nil {
		return m.Tx
	}
	return nil
}

type TransactionReport struct {
	EntityType           *string              `protobuf:"bytes,1,opt,name=entityType" json:"entityType,omitempty"`
	Stats                map[string]string    `protobuf:"bytes,2,rep,name=stats" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SubTx                []*TransactionReport `protobuf:"bytes,3,rep,name=subTx" json:"subTx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionReport) Reset()         { *m = TransactionReport{} }
func (m *TransactionReport) String() string { return proto.CompactTextString(m) }
func (*TransactionReport) ProtoMessage()    {}
func (*TransactionReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{9}
}

func (m *TransactionReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReport.Unmarshal(m, b)
}
func (m *TransactionReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReport.Marshal(b, m, deterministic)
}
func (m *TransactionReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReport.Merge(m, src)
}
func (m *TransactionReport) XXX_Size() int {
	return xxx_messageInfo_TransactionReport.Size(m)
}
func (m *TransactionReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReport.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReport proto.InternalMessageInfo

func (m *TransactionReport) GetEntityType() string {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return ""
}

func (m *TransactionReport) GetStats() map[string]string {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *TransactionReport) GetSubTx() []*TransactionReport {
	if m != nil {
		return m.SubTx
	}
	return nil
}

type QueryReferenceUnit struct {
	BlockId              *int32   `protobuf:"varint,1,opt,name=blockId" json:"blockId,omitempty"`
	LineId               *int32   `protobuf:"varint,2,opt,name=lineId" json:"lineId,omitempty"`
	TokenLocation        *int32   `protobuf:"varint,3,opt,name=tokenLocation" json:"tokenLocation,omitempty"`
	TokenLength          *int32   `protobuf:"varint,4,opt,name=tokenLength" json:"tokenLength,omitempty"`
	TimeStamp            *int64   `protobuf:"varint,5,opt,name=timeStamp" json:"timeStamp,omitempty"`
	EntityId             *int32   `protobuf:"varint,6,opt,name=entityId" json:"entityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReferenceUnit) Reset()         { *m = QueryReferenceUnit{} }
func (m *QueryReferenceUnit) String() string { return proto.CompactTextString(m) }
func (*QueryReferenceUnit) ProtoMessage()    {}
func (*QueryReferenceUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{10}
}

func (m *QueryReferenceUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReferenceUnit.Unmarshal(m, b)
}
func (m *QueryReferenceUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReferenceUnit.Marshal(b, m, deterministic)
}
func (m *QueryReferenceUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferenceUnit.Merge(m, src)
}
func (m *QueryReferenceUnit) XXX_Size() int {
	return xxx_messageInfo_QueryReferenceUnit.Size(m)
}
func (m *QueryReferenceUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferenceUnit.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferenceUnit proto.InternalMessageInfo

func (m *QueryReferenceUnit) GetBlockId() int32 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *QueryReferenceUnit) GetLineId() int32 {
	if m != nil && m.LineId != nil {
		return *m.LineId
	}
	return 0
}

func (m *QueryReferenceUnit) GetTokenLocation() int32 {
	if m != nil && m.TokenLocation != nil {
		return *m.TokenLocation
	}
	return 0
}

func (m *QueryReferenceUnit) GetTokenLength() int32 {
	if m != nil && m.TokenLength != nil {
		return *m.TokenLength
	}
	return 0
}

func (m *QueryReferenceUnit) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *QueryReferenceUnit) GetEntityId() int32 {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return 0
}

type QueryReferenceResponse struct {
	RequestId            *int32                `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	EntityId             *int32                `protobuf:"varint,2,opt,name=entityId" json:"entityId,omitempty"`
	QueryReferenceUnits  []*QueryReferenceUnit `protobuf:"bytes,3,rep,name=queryReferenceUnits" json:"queryReferenceUnits,omitempty"`
	Tx                   *TransactionReport    `protobuf:"bytes,4,opt,name=tx" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QueryReferenceResponse) Reset()         { *m = QueryReferenceResponse{} }
func (m *QueryReferenceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReferenceResponse) ProtoMessage()    {}
func (*QueryReferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{11}
}

func (m *QueryReferenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReferenceResponse.Unmarshal(m, b)
}
func (m *QueryReferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReferenceResponse.Marshal(b, m, deterministic)
}
func (m *QueryReferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferenceResponse.Merge(m, src)
}
func (m *QueryReferenceResponse) XXX_Size() int {
	return xxx_messageInfo_QueryReferenceResponse.Size(m)
}
func (m *QueryReferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferenceResponse proto.InternalMessageInfo

func (m *QueryReferenceResponse) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *QueryReferenceResponse) GetEntityId() int32 {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return 0
}

func (m *QueryReferenceResponse) GetQueryReferenceUnits() []*QueryReferenceUnit {
	if m != nil {
		return m.QueryReferenceUnits
	}
	return nil
}

func (m *QueryReferenceResponse) GetTx() *TransactionReport {
	if m != nil {
		return m.Tx
	}
	return nil
}

type MetricQueryRequest struct {
	RequestId                 *int32    `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	StartTime                 *int64    `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime                   *int64    `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Metadata                  *Metadata `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	UnitOfTimeInSeconds       *int32    `protobuf:"varint,6,opt,name=unitOfTimeInSeconds" json:"unitOfTimeInSeconds,omitempty"`
	TotalTimeFromNowInSeconds *int32    `protobuf:"varint,7,opt,name=totalTimeFromNowInSeconds" json:"totalTimeFromNowInSeconds,omitempty"`
	SelectRegEx               *string   `protobuf:"bytes,8,opt,name=selectRegEx" json:"selectRegEx,omitempty"`
	WhereRegEx                *string   `protobuf:"bytes,9,opt,name=whereRegEx" json:"whereRegEx,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}  `json:"-"`
	XXX_unrecognized          []byte    `json:"-"`
	XXX_sizecache             int32     `json:"-"`
}

func (m *MetricQueryRequest) Reset()         { *m = MetricQueryRequest{} }
func (m *MetricQueryRequest) String() string { return proto.CompactTextString(m) }
func (*MetricQueryRequest) ProtoMessage()    {}
func (*MetricQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{12}
}

func (m *MetricQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricQueryRequest.Unmarshal(m, b)
}
func (m *MetricQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricQueryRequest.Marshal(b, m, deterministic)
}
func (m *MetricQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricQueryRequest.Merge(m, src)
}
func (m *MetricQueryRequest) XXX_Size() int {
	return xxx_messageInfo_MetricQueryRequest.Size(m)
}
func (m *MetricQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricQueryRequest proto.InternalMessageInfo

func (m *MetricQueryRequest) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *MetricQueryRequest) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *MetricQueryRequest) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *MetricQueryRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MetricQueryRequest) GetUnitOfTimeInSeconds() int32 {
	if m != nil && m.UnitOfTimeInSeconds != nil {
		return *m.UnitOfTimeInSeconds
	}
	return 0
}

func (m *MetricQueryRequest) GetTotalTimeFromNowInSeconds() int32 {
	if m != nil && m.TotalTimeFromNowInSeconds != nil {
		return *m.TotalTimeFromNowInSeconds
	}
	return 0
}

func (m *MetricQueryRequest) GetSelectRegEx() string {
	if m != nil && m.SelectRegEx != nil {
		return *m.SelectRegEx
	}
	return ""
}

func (m *MetricQueryRequest) GetWhereRegEx() string {
	if m != nil && m.WhereRegEx != nil {
		return *m.WhereRegEx
	}
	return ""
}

type MetricQueryResponseUnit struct {
	TimeStamp            *int64   `protobuf:"varint,1,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Count                *int32   `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Total                *float64 `protobuf:"fixed64,3,opt,name=total" json:"total,omitempty"`
	Min                  *int32   `protobuf:"varint,4,opt,name=min" json:"min,omitempty"`
	Max                  *int32   `protobuf:"varint,5,opt,name=max" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricQueryResponseUnit) Reset()         { *m = MetricQueryResponseUnit{} }
func (m *MetricQueryResponseUnit) String() string { return proto.CompactTextString(m) }
func (*MetricQueryResponseUnit) ProtoMessage()    {}
func (*MetricQueryResponseUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{13}
}

func (m *MetricQueryResponseUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricQueryResponseUnit.Unmarshal(m, b)
}
func (m *MetricQueryResponseUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricQueryResponseUnit.Marshal(b, m, deterministic)
}
func (m *MetricQueryResponseUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricQueryResponseUnit.Merge(m, src)
}
func (m *MetricQueryResponseUnit) XXX_Size() int {
	return xxx_messageInfo_MetricQueryResponseUnit.Size(m)
}
func (m *MetricQueryResponseUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricQueryResponseUnit.DiscardUnknown(m)
}

var xxx_messageInfo_MetricQueryResponseUnit proto.InternalMessageInfo

func (m *MetricQueryResponseUnit) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *MetricQueryResponseUnit) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *MetricQueryResponseUnit) GetTotal() float64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *MetricQueryResponseUnit) GetMin() int32 {
	if m != nil && m.Min != nil {
		return *m.Min
	}
	return 0
}

func (m *MetricQueryResponseUnit) GetMax() int32 {
	if m != nil && m.Max != nil {
		return *m.Max
	}
	return 0
}

type MetricQueryResponse struct {
	RequestId               *int32                     `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	MetricQueryResponseUnit []*MetricQueryResponseUnit `protobuf:"bytes,2,rep,name=metricQueryResponseUnit" json:"metricQueryResponseUnit,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *MetricQueryResponse) Reset()         { *m = MetricQueryResponse{} }
func (m *MetricQueryResponse) String() string { return proto.CompactTextString(m) }
func (*MetricQueryResponse) ProtoMessage()    {}
func (*MetricQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{14}
}

func (m *MetricQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricQueryResponse.Unmarshal(m, b)
}
func (m *MetricQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricQueryResponse.Marshal(b, m, deterministic)
}
func (m *MetricQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricQueryResponse.Merge(m, src)
}
func (m *MetricQueryResponse) XXX_Size() int {
	return xxx_messageInfo_MetricQueryResponse.Size(m)
}
func (m *MetricQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricQueryResponse proto.InternalMessageInfo

func (m *MetricQueryResponse) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *MetricQueryResponse) GetMetricQueryResponseUnit() []*MetricQueryResponseUnit {
	if m != nil {
		return m.MetricQueryResponseUnit
	}
	return nil
}

// track a token across namespaces or in one namespace or tail
// if start time is missing, now is the start time
// if end time is missing, then continue till a terminate request comes in
type TokenTrackingRequest struct {
	RequestId            *int32      `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	EndTime              *int64      `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Metadata             []*Metadata `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty"`
	IsRegEx              *bool       `protobuf:"varint,4,opt,name=isRegEx" json:"isRegEx,omitempty"`
	Expression           *string     `protobuf:"bytes,5,opt,name=expression" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TokenTrackingRequest) Reset()         { *m = TokenTrackingRequest{} }
func (m *TokenTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*TokenTrackingRequest) ProtoMessage()    {}
func (*TokenTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{15}
}

func (m *TokenTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTrackingRequest.Unmarshal(m, b)
}
func (m *TokenTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTrackingRequest.Marshal(b, m, deterministic)
}
func (m *TokenTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTrackingRequest.Merge(m, src)
}
func (m *TokenTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_TokenTrackingRequest.Size(m)
}
func (m *TokenTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTrackingRequest proto.InternalMessageInfo

func (m *TokenTrackingRequest) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *TokenTrackingRequest) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *TokenTrackingRequest) GetMetadata() []*Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TokenTrackingRequest) GetIsRegEx() bool {
	if m != nil && m.IsRegEx != nil {
		return *m.IsRegEx
	}
	return false
}

func (m *TokenTrackingRequest) GetExpression() string {
	if m != nil && m.Expression != nil {
		return *m.Expression
	}
	return ""
}

type TokenTrackingResponse struct {
	RequestId            *int32    `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	TimeStamp            *int64    `protobuf:"varint,2,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	Expression           *string   `protobuf:"bytes,4,opt,name=expression" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TokenTrackingResponse) Reset()         { *m = TokenTrackingResponse{} }
func (m *TokenTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*TokenTrackingResponse) ProtoMessage()    {}
func (*TokenTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{16}
}

func (m *TokenTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTrackingResponse.Unmarshal(m, b)
}
func (m *TokenTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTrackingResponse.Marshal(b, m, deterministic)
}
func (m *TokenTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTrackingResponse.Merge(m, src)
}
func (m *TokenTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_TokenTrackingResponse.Size(m)
}
func (m *TokenTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTrackingResponse proto.InternalMessageInfo

func (m *TokenTrackingResponse) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *TokenTrackingResponse) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *TokenTrackingResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TokenTrackingResponse) GetExpression() string {
	if m != nil && m.Expression != nil {
		return *m.Expression
	}
	return ""
}

type WorkingEntity struct {
	Ip                   *string  `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port                 *int32   `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	EntityId             *int32   `protobuf:"varint,3,opt,name=entityId" json:"entityId,omitempty"`
	EntityName           *string  `protobuf:"bytes,4,opt,name=entityName" json:"entityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkingEntity) Reset()         { *m = WorkingEntity{} }
func (m *WorkingEntity) String() string { return proto.CompactTextString(m) }
func (*WorkingEntity) ProtoMessage()    {}
func (*WorkingEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{17}
}

func (m *WorkingEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkingEntity.Unmarshal(m, b)
}
func (m *WorkingEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkingEntity.Marshal(b, m, deterministic)
}
func (m *WorkingEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkingEntity.Merge(m, src)
}
func (m *WorkingEntity) XXX_Size() int {
	return xxx_messageInfo_WorkingEntity.Size(m)
}
func (m *WorkingEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkingEntity.DiscardUnknown(m)
}

var xxx_messageInfo_WorkingEntity proto.InternalMessageInfo

func (m *WorkingEntity) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *WorkingEntity) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *WorkingEntity) GetEntityId() int32 {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return 0
}

func (m *WorkingEntity) GetEntityName() string {
	if m != nil && m.EntityName != nil {
		return *m.EntityName
	}
	return ""
}

type CommsEnvelop struct {
	TimeStamp       *int64       `protobuf:"varint,1,opt,name=timeStamp" json:"timeStamp,omitempty"`
	CommandType     *CommandType `protobuf:"varint,2,opt,name=commandType,enum=com.tutsut.proto.CommandType" json:"commandType,omitempty"`
	ExecutionStatus *bool        `protobuf:"varint,4,opt,name=executionStatus" json:"executionStatus,omitempty"`
	// this is for outgoing entity information for operations like registration. Can be optimized to use workingEntity
	Ip                     *string                 `protobuf:"bytes,5,opt,name=ip" json:"ip,omitempty"`
	Port                   *int32                  `protobuf:"varint,6,opt,name=port" json:"port,omitempty"`
	EntityId               *int32                  `protobuf:"varint,7,opt,name=entityId" json:"entityId,omitempty"`
	EntityName             *string                 `protobuf:"bytes,8,opt,name=entityName" json:"entityName,omitempty"`
	ReplyId                *string                 `protobuf:"bytes,9,opt,name=replyId" json:"replyId,omitempty"`
	ReplyMessage           *string                 `protobuf:"bytes,10,opt,name=replyMessage" json:"replyMessage,omitempty"`
	MessageSender          *WorkingEntity          `protobuf:"bytes,11,opt,name=messageSender" json:"messageSender,omitempty"`
	TokenTrackingRequest   *TokenTrackingRequest   `protobuf:"bytes,12,opt,name=tokenTrackingRequest" json:"tokenTrackingRequest,omitempty"`
	QueryRequest           *QueryRequest           `protobuf:"bytes,13,opt,name=queryRequest" json:"queryRequest,omitempty"`
	LeftJoinRequest        *LeftJoinRequest        `protobuf:"bytes,14,opt,name=leftJoinRequest" json:"leftJoinRequest,omitempty"`
	QueryResponse          *QueryResponse          `protobuf:"bytes,15,opt,name=queryResponse" json:"queryResponse,omitempty"`
	TokenTrackingResponse  *TokenTrackingResponse  `protobuf:"bytes,16,opt,name=tokenTrackingResponse" json:"tokenTrackingResponse,omitempty"`
	QueryReferenceResponse *QueryReferenceResponse `protobuf:"bytes,17,opt,name=queryReferenceResponse" json:"queryReferenceResponse,omitempty"`
	MetricQueryRequest     *MetricQueryRequest     `protobuf:"bytes,18,opt,name=metricQueryRequest" json:"metricQueryRequest,omitempty"`
	MetricQueryResponse    *MetricQueryResponse    `protobuf:"bytes,19,opt,name=metricQueryResponse" json:"metricQueryResponse,omitempty"`
	LogLineSet             *LogLineSet             `protobuf:"bytes,20,opt,name=logLineSet" json:"logLineSet,omitempty"`
	WorkingEntity          []*WorkingEntity        `protobuf:"bytes,21,rep,name=workingEntity" json:"workingEntity,omitempty"`
	NameSpaceWorkerTuple   *NameSpaceWorkerTuple   `protobuf:"bytes,22,opt,name=nameSpaceWorkerTuple" json:"nameSpaceWorkerTuple,omitempty"`
	QueryRequestBlockList  *QueryRequestBlockList  `protobuf:"bytes,23,opt,name=queryRequestBlockList" json:"queryRequestBlockList,omitempty"`
	KeyForLogLineSetWrite  *string                 `protobuf:"bytes,24,opt,name=keyForLogLineSetWrite" json:"keyForLogLineSetWrite,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *CommsEnvelop) Reset()         { *m = CommsEnvelop{} }
func (m *CommsEnvelop) String() string { return proto.CompactTextString(m) }
func (*CommsEnvelop) ProtoMessage()    {}
func (*CommsEnvelop) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0402b27e0ae81ad, []int{18}
}

func (m *CommsEnvelop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommsEnvelop.Unmarshal(m, b)
}
func (m *CommsEnvelop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommsEnvelop.Marshal(b, m, deterministic)
}
func (m *CommsEnvelop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommsEnvelop.Merge(m, src)
}
func (m *CommsEnvelop) XXX_Size() int {
	return xxx_messageInfo_CommsEnvelop.Size(m)
}
func (m *CommsEnvelop) XXX_DiscardUnknown() {
	xxx_messageInfo_CommsEnvelop.DiscardUnknown(m)
}

var xxx_messageInfo_CommsEnvelop proto.InternalMessageInfo

func (m *CommsEnvelop) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *CommsEnvelop) GetCommandType() CommandType {
	if m != nil && m.CommandType != nil {
		return *m.CommandType
	}
	return CommandType_ACK
}

func (m *CommsEnvelop) GetExecutionStatus() bool {
	if m != nil && m.ExecutionStatus != nil {
		return *m.ExecutionStatus
	}
	return false
}

func (m *CommsEnvelop) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *CommsEnvelop) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *CommsEnvelop) GetEntityId() int32 {
	if m != nil && m.EntityId != nil {
		return *m.EntityId
	}
	return 0
}

func (m *CommsEnvelop) GetEntityName() string {
	if m != nil && m.EntityName != nil {
		return *m.EntityName
	}
	return ""
}

func (m *CommsEnvelop) GetReplyId() string {
	if m != nil && m.ReplyId != nil {
		return *m.ReplyId
	}
	return ""
}

func (m *CommsEnvelop) GetReplyMessage() string {
	if m != nil && m.ReplyMessage != nil {
		return *m.ReplyMessage
	}
	return ""
}

func (m *CommsEnvelop) GetMessageSender() *WorkingEntity {
	if m != nil {
		return m.MessageSender
	}
	return nil
}

func (m *CommsEnvelop) GetTokenTrackingRequest() *TokenTrackingRequest {
	if m != nil {
		return m.TokenTrackingRequest
	}
	return nil
}

func (m *CommsEnvelop) GetQueryRequest() *QueryRequest {
	if m != nil {
		return m.QueryRequest
	}
	return nil
}

func (m *CommsEnvelop) GetLeftJoinRequest() *LeftJoinRequest {
	if m != nil {
		return m.LeftJoinRequest
	}
	return nil
}

func (m *CommsEnvelop) GetQueryResponse() *QueryResponse {
	if m != nil {
		return m.QueryResponse
	}
	return nil
}

func (m *CommsEnvelop) GetTokenTrackingResponse() *TokenTrackingResponse {
	if m != nil {
		return m.TokenTrackingResponse
	}
	return nil
}

func (m *CommsEnvelop) GetQueryReferenceResponse() *QueryReferenceResponse {
	if m != nil {
		return m.QueryReferenceResponse
	}
	return nil
}

func (m *CommsEnvelop) GetMetricQueryRequest() *MetricQueryRequest {
	if m != nil {
		return m.MetricQueryRequest
	}
	return nil
}

func (m *CommsEnvelop) GetMetricQueryResponse() *MetricQueryResponse {
	if m != nil {
		return m.MetricQueryResponse
	}
	return nil
}

func (m *CommsEnvelop) GetLogLineSet() *LogLineSet {
	if m != nil {
		return m.LogLineSet
	}
	return nil
}

func (m *CommsEnvelop) GetWorkingEntity() []*WorkingEntity {
	if m != nil {
		return m.WorkingEntity
	}
	return nil
}

func (m *CommsEnvelop) GetNameSpaceWorkerTuple() *NameSpaceWorkerTuple {
	if m != nil {
		return m.NameSpaceWorkerTuple
	}
	return nil
}

func (m *CommsEnvelop) GetQueryRequestBlockList() *QueryRequestBlockList {
	if m != nil {
		return m.QueryRequestBlockList
	}
	return nil
}

func (m *CommsEnvelop) GetKeyForLogLineSetWrite() string {
	if m != nil && m.KeyForLogLineSetWrite != nil {
		return *m.KeyForLogLineSetWrite
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "com.tutsut.proto.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "com.tutsut.proto.Metadata.NamespaceEntry")
	proto.RegisterType((*LogLine)(nil), "com.tutsut.proto.LogLine")
	proto.RegisterType((*LogLineSet)(nil), "com.tutsut.proto.LogLineSet")
	proto.RegisterType((*NameSpaceWorkerTuple)(nil), "com.tutsut.proto.NameSpaceWorkerTuple")
	proto.RegisterType((*LogBlock)(nil), "com.tutsut.proto.LogBlock")
	proto.RegisterType((*LogBlock_Header)(nil), "com.tutsut.proto.LogBlock.Header")
	proto.RegisterType((*QueryRequest)(nil), "com.tutsut.proto.QueryRequest")
	proto.RegisterType((*QueryRequestBlockList)(nil), "com.tutsut.proto.QueryRequestBlockList")
	proto.RegisterType((*LeftJoinRequest)(nil), "com.tutsut.proto.LeftJoinRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.tutsut.proto.QueryResponse")
	proto.RegisterType((*TransactionReport)(nil), "com.tutsut.proto.TransactionReport")
	proto.RegisterMapType((map[string]string)(nil), "com.tutsut.proto.TransactionReport.StatsEntry")
	proto.RegisterType((*QueryReferenceUnit)(nil), "com.tutsut.proto.QueryReferenceUnit")
	proto.RegisterType((*QueryReferenceResponse)(nil), "com.tutsut.proto.QueryReferenceResponse")
	proto.RegisterType((*MetricQueryRequest)(nil), "com.tutsut.proto.MetricQueryRequest")
	proto.RegisterType((*MetricQueryResponseUnit)(nil), "com.tutsut.proto.MetricQueryResponseUnit")
	proto.RegisterType((*MetricQueryResponse)(nil), "com.tutsut.proto.MetricQueryResponse")
	proto.RegisterType((*TokenTrackingRequest)(nil), "com.tutsut.proto.TokenTrackingRequest")
	proto.RegisterType((*TokenTrackingResponse)(nil), "com.tutsut.proto.TokenTrackingResponse")
	proto.RegisterType((*WorkingEntity)(nil), "com.tutsut.proto.WorkingEntity")
	proto.RegisterType((*CommsEnvelop)(nil), "com.tutsut.proto.CommsEnvelop")
}

func init() { proto.RegisterFile("Block.proto", fileDescriptor_c0402b27e0ae81ad) }

var fileDescriptor_c0402b27e0ae81ad = []byte{
	// 1371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x8e, 0x1b, 0xc5,
	0x13, 0xd7, 0xd8, 0x3b, 0xbb, 0x76, 0x79, 0x3f, 0x7b, 0x3f, 0x32, 0xb1, 0x92, 0xfc, 0xf7, 0x3f,
	0x04, 0x58, 0x2e, 0x16, 0x0a, 0x10, 0x05, 0x14, 0x09, 0x29, 0x64, 0x03, 0x1b, 0x9c, 0x20, 0xda,
	0x86, 0x48, 0x48, 0x68, 0x99, 0x8c, 0x6b, 0xbd, 0xa3, 0x9d, 0xe9, 0xf1, 0xce, 0xb4, 0xb3, 0x5e,
	0xce, 0x48, 0x88, 0x0b, 0x12, 0x17, 0x04, 0xcf, 0xc0, 0x81, 0x67, 0xe0, 0xc6, 0x13, 0x70, 0xe5,
	0x0d, 0x78, 0x00, 0x4e, 0xa8, 0x7b, 0xda, 0xf6, 0xb4, 0xa7, 0x8d, 0x67, 0x73, 0xe2, 0xd6, 0x5d,
	0xdd, 0xf5, 0x9b, 0xaa, 0xea, 0xaa, 0x5f, 0x75, 0x0f, 0x34, 0x1e, 0x84, 0xb1, 0x7f, 0xd6, 0x1a,
	0x24, 0x31, 0x8f, 0xc9, 0xa6, 0x1f, 0x47, 0x2d, 0x3e, 0xe4, 0xe9, 0x90, 0x67, 0x92, 0xe6, 0xd6,
	0x07, 0x71, 0x14, 0x79, 0xac, 0xd7, 0xbd, 0x1c, 0x60, 0x26, 0x72, 0x7f, 0xb0, 0xa0, 0xf6, 0x04,
	0xb9, 0xd7, 0xf3, 0xb8, 0x47, 0x3e, 0x84, 0x3a, 0xf3, 0x22, 0x4c, 0x07, 0x9e, 0x8f, 0x8e, 0xb5,
	0x5f, 0x3d, 0x68, 0xdc, 0x79, 0xa3, 0x35, 0x8b, 0xd2, 0x1a, 0x6f, 0x6f, 0x3d, 0x1d, 0xef, 0x3d,
	0x64, 0x3c, 0xb9, 0xa4, 0x53, 0xdd, 0xe6, 0x7d, 0x58, 0xd7, 0x17, 0xc9, 0x26, 0x54, 0xcf, 0xf0,
	0xd2, 0xb1, 0xf6, 0xad, 0x83, 0x3a, 0x15, 0x43, 0xb2, 0x03, 0xf6, 0x0b, 0x2f, 0x1c, 0xa2, 0x53,
	0x91, 0xb2, 0x6c, 0xf2, 0x5e, 0xe5, 0x9e, 0xe5, 0x3e, 0x80, 0x95, 0x76, 0xdc, 0x6f, 0x07, 0x0c,
	0xc9, 0x4d, 0x00, 0x1e, 0x44, 0x78, 0x9c, 0x72, 0x2f, 0x1a, 0x48, 0xed, 0x2a, 0xad, 0x0b, 0x49,
	0x47, 0x08, 0x88, 0x03, 0x2b, 0x7e, 0xcc, 0x38, 0x32, 0xae, 0x50, 0xc6, 0x53, 0xf7, 0x7b, 0x0b,
	0x40, 0x81, 0x74, 0x90, 0x1b, 0x3e, 0x7f, 0x17, 0x6a, 0x91, 0x72, 0x44, 0xea, 0x36, 0xee, 0x34,
	0xe7, 0xbb, 0x4a, 0x27, 0x7b, 0xc9, 0x5d, 0xa8, 0x87, 0x71, 0xff, 0x38, 0x0c, 0x18, 0xa6, 0x4e,
	0x55, 0xc6, 0xe8, 0x7a, 0x51, 0x51, 0x7d, 0x9a, 0xd6, 0xc2, 0x6c, 0x90, 0xba, 0xdf, 0x59, 0xb0,
	0x23, 0x62, 0xd2, 0x11, 0x31, 0x79, 0x16, 0x27, 0x67, 0x98, 0x74, 0x87, 0x83, 0x10, 0x35, 0x43,
	0xac, 0x2b, 0x18, 0x72, 0x13, 0x20, 0xe5, 0x5e, 0xc2, 0x8f, 0x45, 0x38, 0xa4, 0x0b, 0x55, 0x5a,
	0x97, 0x92, 0x6e, 0x10, 0x21, 0x69, 0x42, 0xed, 0x42, 0x7e, 0xe5, 0xa8, 0xe7, 0x54, 0xf7, 0xad,
	0x03, 0x9b, 0x4e, 0xe6, 0xee, 0x37, 0x15, 0xa8, 0xb5, 0xe3, 0xbe, 0x4c, 0x16, 0xf2, 0x10, 0x56,
	0x9f, 0x8b, 0xc1, 0xf1, 0x29, 0x7a, 0x3d, 0x4c, 0x94, 0x0d, 0xff, 0x37, 0xfa, 0x94, 0xa5, 0xd7,
	0x47, 0x72, 0x23, 0x6d, 0x48, 0xb5, 0x6c, 0xa2, 0x87, 0xa5, 0x52, 0x3a, 0x2c, 0xcd, 0xaf, 0x61,
	0x59, 0x21, 0xe8, 0xfe, 0x58, 0xb3, 0xfe, 0x5c, 0x87, 0x1a, 0xb2, 0x5e, 0xde, 0xd9, 0x15, 0x64,
	0x3d, 0xb9, 0x94, 0x8f, 0x60, 0xb5, 0x7c, 0x04, 0xdd, 0xbf, 0x2d, 0x58, 0xfd, 0x74, 0x88, 0xc9,
	0x25, 0xc5, 0xf3, 0x21, 0xa6, 0x9c, 0xdc, 0x80, 0x7a, 0x92, 0x0d, 0x8f, 0x7a, 0xd2, 0x02, 0x9b,
	0x4e, 0x05, 0x8b, 0x02, 0x9e, 0x37, 0xb0, 0x3a, 0xdf, 0xc0, 0xa5, 0x2b, 0x1c, 0xf1, 0x3e, 0x34,
	0x52, 0x0c, 0xd1, 0xe7, 0x14, 0xfb, 0x87, 0x23, 0xc7, 0x96, 0xd9, 0x9b, 0x17, 0x91, 0x5b, 0x00,
	0x17, 0xa7, 0x98, 0x60, 0xb6, 0x61, 0x59, 0x6e, 0xc8, 0x49, 0x44, 0x81, 0x04, 0x69, 0xb6, 0xb8,
	0xb2, 0x6f, 0x1d, 0xd4, 0xe8, 0x78, 0xea, 0xfe, 0x6a, 0xc1, 0x6e, 0xde, 0x79, 0x79, 0xb4, 0xed,
	0x60, 0x61, 0x14, 0xf4, 0xba, 0xa9, 0xbe, 0xac, 0x2f, 0xd5, 0x45, 0xbe, 0x2c, 0xcd, 0xfa, 0xe2,
	0xfe, 0x62, 0xc1, 0x46, 0x1b, 0x4f, 0xf8, 0xe3, 0x38, 0x60, 0xe3, 0x13, 0x7b, 0x0c, 0x9b, 0x21,
	0x9e, 0xf0, 0xbc, 0x23, 0x2a, 0x81, 0x6f, 0x15, 0xad, 0xca, 0xef, 0xa2, 0x05, 0x3d, 0xd2, 0x86,
	0xad, 0x24, 0xe8, 0x9f, 0xea, 0x60, 0x95, 0x52, 0x60, 0x45, 0x45, 0xf7, 0x67, 0x0b, 0xd6, 0x94,
	0x20, 0x1d, 0xc4, 0x2c, 0xc5, 0x05, 0x71, 0x7d, 0x07, 0x26, 0x45, 0x71, 0x85, 0xfa, 0x21, 0x6f,
	0x41, 0x85, 0x8f, 0x54, 0x52, 0xbd, 0x52, 0x54, 0xe8, 0x26, 0x1e, 0x4b, 0x3d, 0x9f, 0x07, 0x31,
	0xa3, 0x38, 0x88, 0x13, 0x4e, 0x2b, 0x7c, 0xe4, 0xfe, 0x65, 0xc1, 0x56, 0x61, 0x45, 0xc4, 0x1f,
	0x19, 0x0f, 0xf8, 0xa5, 0x68, 0x0f, 0x8a, 0x2a, 0x73, 0x12, 0xf2, 0x10, 0xec, 0x94, 0x7b, 0x7c,
	0x6c, 0x5e, 0xab, 0xc4, 0xd7, 0x5a, 0x1d, 0xa1, 0x90, 0xb5, 0x87, 0x4c, 0x99, 0xbc, 0x0b, 0x76,
	0x3a, 0x7c, 0xde, 0x1d, 0x29, 0xee, 0x2c, 0x65, 0x73, 0xa6, 0xd1, 0xbc, 0x07, 0x30, 0xc5, 0xbb,
	0x52, 0x47, 0xf9, 0xdd, 0x02, 0xa2, 0x0e, 0xe3, 0x04, 0x13, 0x64, 0x3e, 0x7e, 0xc6, 0x02, 0x2e,
	0xaa, 0x43, 0x72, 0xd8, 0xe4, 0x3c, 0xc6, 0x53, 0xb2, 0x07, 0xcb, 0x82, 0xca, 0x8e, 0x7a, 0x12,
	0xcb, 0xa6, 0x6a, 0x46, 0x6e, 0xc3, 0x1a, 0x8f, 0xcf, 0x90, 0xb5, 0x63, 0xdf, 0x13, 0x06, 0x2a,
	0x6a, 0xd5, 0x85, 0x22, 0xd7, 0x33, 0x01, 0xb2, 0x3e, 0x3f, 0x95, 0xa7, 0x63, 0xd3, 0xbc, 0x48,
	0xe4, 0xc2, 0xa4, 0x8b, 0xc9, 0xba, 0xd6, 0xda, 0x5a, 0x53, 0x50, 0x89, 0x88, 0xfb, 0x51, 0x4f,
	0xd6, 0xb4, 0x4d, 0x27, 0x73, 0xf7, 0x4f, 0x0b, 0xf6, 0x74, 0x57, 0x4a, 0x26, 0x58, 0x1e, 0xb4,
	0xa2, 0x83, 0x92, 0xcf, 0x61, 0xfb, 0xbc, 0x10, 0x9e, 0x71, 0x7b, 0xbb, 0x3d, 0x37, 0xf9, 0x73,
	0x9b, 0xa9, 0x09, 0xe0, 0xe5, 0xb2, 0xf3, 0x8f, 0x0a, 0x90, 0x27, 0xc8, 0x93, 0xc0, 0xff, 0x4f,
	0x93, 0xf3, 0x9b, 0xb0, 0x3d, 0x64, 0x01, 0xff, 0xe4, 0x44, 0xa0, 0x1c, 0xb1, 0x0e, 0xfa, 0x31,
	0xeb, 0xa5, 0xea, 0xbc, 0x4c, 0x4b, 0xe4, 0x3e, 0x5c, 0xe7, 0x31, 0xf7, 0x42, 0x21, 0x7d, 0x94,
	0xc4, 0xd1, 0xd3, 0xf8, 0x62, 0xaa, 0xb7, 0x22, 0xf5, 0xe6, 0x6f, 0x98, 0x25, 0xd0, 0xda, 0x22,
	0x02, 0xad, 0x17, 0x08, 0xf4, 0x5b, 0x0b, 0xae, 0x69, 0x81, 0xcd, 0xf2, 0x46, 0x96, 0x82, 0x96,
	0x90, 0x85, 0x7b, 0xd6, 0x0e, 0xd8, 0x7e, 0x3c, 0x54, 0xb7, 0x2c, 0x9b, 0x66, 0x13, 0x21, 0x95,
	0xe6, 0xca, 0x88, 0x5a, 0x34, 0x9b, 0x88, 0xba, 0x8c, 0x02, 0xa6, 0x92, 0x5e, 0x0c, 0xa5, 0xc4,
	0xcb, 0xda, 0x97, 0x90, 0x78, 0x23, 0xf7, 0x27, 0x0b, 0xb6, 0x0d, 0x96, 0x2c, 0x38, 0x63, 0x1f,
	0xae, 0x45, 0x66, 0xf3, 0x15, 0x25, 0x99, 0x2f, 0xab, 0x26, 0x05, 0x3a, 0x0f, 0xc9, 0xfd, 0xcd,
	0x82, 0x9d, 0xae, 0xa8, 0xd4, 0x6e, 0xe2, 0xf9, 0x67, 0x01, 0xeb, 0x97, 0xcb, 0xbf, 0xd2, 0xd7,
	0x93, 0xf2, 0x1d, 0x33, 0xd7, 0xbb, 0x97, 0xb4, 0xde, 0x2d, 0x99, 0x7a, 0x34, 0x48, 0x30, 0x4d,
	0x05, 0x05, 0xd9, 0x8a, 0xa9, 0x27, 0x12, 0xd1, 0x29, 0x77, 0x67, 0x7c, 0x28, 0x15, 0x60, 0x2d,
	0x09, 0x2a, 0xb3, 0x49, 0xf0, 0x92, 0xd7, 0xac, 0x19, 0x6b, 0x97, 0x0a, 0xd6, 0xc6, 0xb0, 0x26,
	0xee, 0xc3, 0x01, 0xeb, 0x1f, 0x4a, 0x3e, 0x22, 0xeb, 0x50, 0x09, 0x06, 0x8a, 0xd8, 0x2b, 0xc1,
	0x80, 0x10, 0x58, 0x12, 0xe4, 0xa0, 0x92, 0x4f, 0x8e, 0x35, 0x36, 0xab, 0xce, 0xb0, 0xd9, 0xa4,
	0x91, 0x89, 0xfb, 0xf6, 0xe4, 0x83, 0x13, 0x89, 0xfb, 0x63, 0x03, 0x56, 0xc5, 0x4b, 0x28, 0x3d,
	0x64, 0x2f, 0x30, 0x8c, 0x07, 0x0b, 0x92, 0xff, 0x7d, 0x68, 0xf8, 0xd3, 0x77, 0x93, 0xb4, 0x62,
	0xfd, 0xce, 0xcd, 0xa2, 0xeb, 0xb9, 0xc7, 0x15, 0xcd, 0x6b, 0x90, 0x03, 0xd8, 0xc0, 0x11, 0xfa,
	0x43, 0xc1, 0x73, 0xa2, 0x81, 0x0d, 0x53, 0x75, 0xa0, 0xb3, 0x62, 0xe5, 0xb9, 0x5d, 0xf0, 0x7c,
	0x79, 0x8e, 0xe7, 0x2b, 0xff, 0xea, 0x79, 0x6d, 0xd6, 0x73, 0x91, 0x52, 0x09, 0x0e, 0x42, 0xa1,
	0x9a, 0xd1, 0xc3, 0x78, 0x4a, 0x5c, 0x58, 0x95, 0xc3, 0x27, 0x98, 0xa6, 0x5e, 0x1f, 0x1d, 0x90,
	0xcb, 0x9a, 0x8c, 0x1c, 0xc2, 0x5a, 0x94, 0x0d, 0x3b, 0xc8, 0xc4, 0x53, 0xa1, 0x21, 0xb3, 0xe0,
	0x7f, 0xc5, 0x50, 0x68, 0xe7, 0x49, 0x75, 0x2d, 0xf2, 0x05, 0xec, 0x70, 0x43, 0x81, 0x39, 0xab,
	0x12, 0xed, 0x35, 0x43, 0x9b, 0x30, 0xec, 0xa6, 0x46, 0x0c, 0xf2, 0x00, 0x56, 0xcf, 0xf3, 0xd7,
	0xb7, 0xb5, 0x52, 0xd7, 0x37, 0x4d, 0x87, 0x7c, 0x0c, 0x1b, 0xa1, 0x7e, 0xcd, 0x74, 0xd6, 0xe7,
	0xbe, 0x89, 0xf4, 0x8d, 0x74, 0x56, 0x53, 0xc4, 0xec, 0x3c, 0xcf, 0x31, 0xce, 0xc6, 0xbc, 0x98,
	0x69, 0x54, 0x44, 0x75, 0x2d, 0xf2, 0x25, 0xec, 0x72, 0x53, 0x41, 0x3b, 0x9b, 0x12, 0xee, 0xf5,
	0x85, 0x41, 0x53, 0xb0, 0x66, 0x14, 0xf2, 0x15, 0xec, 0x9d, 0x1b, 0xef, 0x14, 0xce, 0x96, 0xc4,
	0x3f, 0x58, 0x74, 0x05, 0x98, 0x7c, 0x60, 0x0e, 0x0e, 0xe9, 0x02, 0x89, 0x0a, 0x3d, 0xdd, 0x21,
	0x12, 0xfd, 0xf6, 0x02, 0xda, 0xce, 0x42, 0x6b, 0xd0, 0x27, 0xcf, 0x60, 0xdb, 0xc0, 0xe3, 0xce,
	0xb6, 0x84, 0x7d, 0xb5, 0x54, 0x37, 0xa0, 0x26, 0x04, 0x72, 0x1f, 0x20, 0x9c, 0xfc, 0x3d, 0x70,
	0x76, 0x24, 0xde, 0x8d, 0xb9, 0xf7, 0xf1, 0x0e, 0x72, 0x9a, 0xdb, 0x2f, 0x0e, 0xfd, 0x22, 0x5f,
	0x01, 0xce, 0xae, 0xa4, 0xfd, 0xc5, 0x85, 0xa2, 0x69, 0x89, 0x42, 0x61, 0x86, 0x3f, 0x06, 0xce,
	0xde, 0xbc, 0x42, 0x31, 0xfd, 0x5f, 0xa0, 0x46, 0x0c, 0x91, 0x50, 0xe7, 0xa6, 0xd7, 0x9f, 0x73,
	0x6d, 0x5e, 0x42, 0x19, 0x1f, 0x8b, 0xd4, 0x8c, 0x42, 0xde, 0x86, 0xdd, 0x33, 0xbc, 0x7c, 0x14,
	0x27, 0xd3, 0x08, 0x3d, 0x4b, 0x02, 0x8e, 0x8e, 0x23, 0x79, 0xc5, 0xbc, 0xf8, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0x22, 0x38, 0x0b, 0xbf, 0x12, 0x00, 0x00,
}
